version: '3.8'

services:
  user:
    image: rednecksinc/brugerservice:latest
    ports:
      - "5002:80"
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CollectionName=Users
      - ConnectionString=mongodb://mongodb:27017
      - DatabaseName=UsersDb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
      - "7017:7017"
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user
    ports:
      - "4000:4000"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  docs: