version: '3.8'

services:
  user:
    image: rednecksinc/brugerservice:latest
    ports:
      - "5002:80"
    networks:
      - default

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user
    ports:
      - "4000:4000"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mongodb_data:
  docs: