version: '3.8'

services:
  user:
    image: rednecksinc/brugerservice:latest
    ports:
      - "5002:80"
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - collectionName="Users"
      - connectionString="mongodb://mongodb:27018"
      - databaseName="UsersDb"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user
    ports:
      - "4000:4000"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  docs: