name: Docker Image Bruger

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD   
        
    - name: Build the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker build . --file BrugerService/Dockerfile --tag ${DOCKER_USER}/brugerservice:latest-dev 
      
    - name: Push image to Docker Hub
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker push ${DOCKER_USER}/brugerservice:latest-dev
